### ISSUE TITLE
Looks Awesome.

### ISSUE THREAD

**Issue by SweatyToast** [ConnorsApps/snapcast-ui#2]
Any tips on how to install this? Thanks!

**Comment by ConnorsApps** [comment]
Good question, this is just a static site built using React JS. You can use docker to package up this app and run it anywhere or just serve the static html, js, and css files. I'll make a doc with steps.

**Comment by ConnorsApps** [comment]
Checkout the README and let me know if there is anything unclear or unanswered.

**Comment by SweatyToast** [comment]
I tried to install this using docker-compose but im getting an error when trying to install 

ERROR: Service 'frontend' failed to build: When using COPY with more than one source file, the destination must be a directory and end with a /

I tried changing the dockerfile to 

COPY package*.json ./

Still running into problems don't really know what's going wrong here.

**Comment by ConnorsApps** [comment]
The Dockerfile you're using running locally is at `.docker/DockerfileLocal`. I've updated the Dockerfiles.

**Comment by SweatyToast** [comment]
Thanks I've been running this for a while works good! Very clean UI.
